# Generated by Django 5.2.4 on 2026-01-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reference",
                    models.CharField(
                        help_text="Human readable transaction number", max_length=100
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("sales", "Sales"),
                            ("purchase", "Purchase"),
                            ("adjustment", "Stock Adjustment"),
                            ("transfer", "Stock Transfer"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("transaction_date", models.DateField()),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "business_transactions",
                "ordering": ["-transaction_date"],
            },
        ),
        migrations.CreateModel(
            name="TransactionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=14)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=14)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=14)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "business_transaction_items",
                "ordering": ["id"],
            },
        ),
    ]
