# Generated by Django 5.2.4 on 2026-03-12 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reference",
                    models.CharField(
                        help_text="Human readable transaction number", max_length=100
                    ),
                ),
                (
                    "subtype",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("direct", "Direct"),
                            ("order", "Order Based"),
                            ("manufacture", "Manufacturing"),
                            ("consignment", "Consignment"),
                            ("service", "Service"),
                        ],
                        help_text="Business flow subtype",
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("transaction_date", models.DateField()),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "business_transactions",
                "ordering": ["-transaction_date"],
            },
        ),
        migrations.CreateModel(
            name="TransactionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=14)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=14)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=14)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "business_transaction_items",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="TransactionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=100)),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("in", "In"),
                            ("out", "Out"),
                            ("internal", "Internal"),
                        ],
                        max_length=20,
                    ),
                ),
                ("require_customer", models.BooleanField(default=False)),
                ("require_partner", models.BooleanField(default=False)),
                ("affect_stock", models.BooleanField(default=True)),
                ("auto_post", models.BooleanField(default=False)),
                ("allow_anonymous", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "business_transaction_types",
                "ordering": ["code"],
            },
        ),
    ]
