# Generated by Django 5.2.4 on 2026-02-01 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business_transactions", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="subtype",
            field=models.CharField(
                blank=True,
                choices=[
                    ("direct", "Direct"),
                    ("order", "Order Based"),
                    ("manufacture", "Manufacturing"),
                    ("consignment", "Consignment"),
                    ("service", "Service"),
                ],
                help_text="Business flow subtype",
                max_length=30,
                null=True,
            ),
        ),
    ]
