# Generated by Django 5.2.4 on 2026-01-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr_employees", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="user_id",
            field=models.UUIDField(
                blank=True, help_text="Reference to core.users.User.id", null=True
            ),
        ),
    ]
