# Generated by Django 5.2.4 on 2026-02-14 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core_tenants", "0003_tenant_branding"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UIWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("extensions", models.JSONField(blank=True, default=dict)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("banner", "Banner"),
                            ("video", "Video"),
                            ("calendar", "Calendar"),
                            ("market", "Market"),
                            ("weather", "Weather"),
                            ("kpi", "KPI"),
                            ("reminder", "Reminder"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("dashboard.main", "Dashboard Main"),
                            ("dashboard.sidebar", "Dashboard Sidebar"),
                            ("app.main", "App Main"),
                            ("app.sidebar", "App Sidebar"),
                        ],
                        max_length=100,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Widget configuration payload",
                    ),
                ),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("target_roles", models.JSONField(blank=True, default=list)),
                ("target_permissions", models.JSONField(blank=True, default=list)),
                ("target_apps", models.JSONField(blank=True, default=list)),
                ("order", models.IntegerField(default=50)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core_tenants.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "core_widgets",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
