# Generated by Django 5.2.4 on 2026-04-30 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core_widgets", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uiwidget",
            name="target_apps",
        ),
    ]
