# Generated by Django 5.2.4 on 2026-04-13 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core_wallet_withdrawal", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="withdrawal",
            new_name="core_wallet_tenant__3ebba3_idx",
            old_name="wallet_with_tenant__18863e_idx",
        ),
        migrations.AlterModelTable(
            name="withdrawal",
            table="core_wallet_withdrawals",
        ),
    ]
