# Generated by Django 5.2.4 on 2026-04-11 01:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_geo_countries", "0002_initial"),
        ("core_tenants", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="country",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="country",
            name="code",
            field=models.CharField(max_length=3),
        ),
        migrations.AddIndex(
            model_name="country",
            index=models.Index(
                fields=["tenant", "code"], name="core_countr_tenant__f884c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="country",
            index=models.Index(
                fields=["tenant", "name"], name="core_countr_tenant__ce8464_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="country",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="uniq_country_tenant_code"
            ),
        ),
    ]
