# Generated by Django 5.2.4 on 2026-04-11 02:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core_geo_countries",
            "0003_alter_country_unique_together_alter_country_code_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="country",
            name="uniq_country_tenant_code",
        ),
        migrations.RemoveIndex(
            model_name="country",
            name="core_countr_tenant__f884c0_idx",
        ),
        migrations.RemoveIndex(
            model_name="country",
            name="core_countr_tenant__ce8464_idx",
        ),
        migrations.RemoveField(
            model_name="country",
            name="tenant",
        ),
        migrations.AddConstraint(
            model_name="country",
            constraint=models.UniqueConstraint(
                fields=("code",), name="uniq_country_code"
            ),
        ),
    ]
