# Generated by Django 5.2.4 on 2026-03-12 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("customer", "customer"),
                            ("partner", "partner"),
                            ("viewer", "viewer"),
                            ("staff", "staff"),
                            ("supervisor", "supervisor"),
                            ("manager", "manager"),
                            ("gm", "gm"),
                            ("director", "director"),
                            ("advisor", "advisor"),
                            ("cashier", "cashier"),
                            ("warehouse", "warehouse"),
                            ("operator", "operator"),
                            ("technician", "technician"),
                            ("finance", "finance"),
                            ("admin", "admin"),
                            ("owner", "owner"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "access_level",
                    models.PositiveIntegerField(
                        help_text="Semakin besar, semakin tinggi akses"
                    ),
                ),
                ("is_system", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "core_roles",
                "ordering": ["access_level"],
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "core_user_roles",
            },
        ),
    ]
