# Generated by Django 5.2.4 on 2026-02-20 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_roles", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="is_system",
            field=models.BooleanField(default=True),
        ),
    ]
