# Generated by Django 5.2.4 on 2026-03-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_roles", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="is_default",
            field=models.BooleanField(
                default=False, help_text="Default role for new users in this tenant"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="code",
            field=models.CharField(
                choices=[
                    ("guest", "guest"),
                    ("customer", "customer"),
                    ("partner", "partner"),
                    ("viewer", "viewer"),
                    ("staff", "staff"),
                    ("supervisor", "supervisor"),
                    ("manager", "manager"),
                    ("gm", "gm"),
                    ("director", "director"),
                    ("advisor", "advisor"),
                    ("cashier", "cashier"),
                    ("warehouse", "warehouse"),
                    ("operator", "operator"),
                    ("technician", "technician"),
                    ("finance", "finance"),
                    ("admin", "admin"),
                    ("owner", "owner"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
