# Generated by Django 5.2.4 on 2026-04-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_wallet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallettransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("topup", "Topup"),
                    ("payment", "Payment"),
                    ("refund", "Refund"),
                    ("escrow_hold", "Escrow Hold"),
                    ("escrow_release", "Escrow Release"),
                    ("adjustment", "Adjustment"),
                    ("withdraw", "Withdraw"),
                    ("withdraw_fee", "Withdraw Fee"),
                ],
                max_length=50,
            ),
        ),
    ]
