# Generated by Django 5.2.4 on 2026-04-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_wallet", "0002_alter_wallettransaction_transaction_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallettransaction",
            name="meta",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
