# Generated by Django 5.2.4 on 2026-03-12 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("extensions", models.JSONField(blank=True, default=dict)),
                ("name", models.CharField(max_length=100)),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField()),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="Custom metadata for vertical/business modules",
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "core_schedule_shifts",
                "ordering": ["start_datetime"],
            },
        ),
        migrations.CreateModel(
            name="ShiftParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        help_text="Optional role inside shift (leader, backup, etc)",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "db_table": "core_schedule_shift_participants",
            },
        ),
    ]
