# Generated by Django 5.2.4 on 2026-03-12 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApotekCustomerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medical_note", models.TextField(blank=True)),
                ("allergies", models.TextField(blank=True)),
                ("requires_prescription", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Apotek Customer Profile",
                "verbose_name_plural": "Apotek Customer Profiles",
                "db_table": "verticals_apotek_customer_profile",
            },
        ),
    ]
