# Generated by Django 5.2.4 on 2026-02-04 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("business_customers", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApotekCustomerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medical_note", models.TextField(blank=True)),
                ("allergies", models.TextField(blank=True)),
                ("requires_prescription", models.BooleanField(default=False)),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apotek_profile",
                        to="business_customers.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Apotek Customer Profile",
                "verbose_name_plural": "Apotek Customer Profiles",
            },
        ),
    ]
