# Generated by Django 5.2.4 on 2026-02-04 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apotek", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="apotekcustomerprofile",
            table="verticals_apotek_customer_profile",
        ),
    ]
