# Generated by Django 5.2.4 on 2026-03-12 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("apotek", "0001_initial"),
        ("business_customers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apotekcustomerprofile",
            name="customer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="apotek_profile",
                to="business_customers.customer",
            ),
        ),
    ]
