# Generated by Django 5.2.4 on 2026-03-12 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Unique tax code, e.g. VAT_ID, PPH_23", max_length=30
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("percentage", "Percentage"),
                            ("fixed", "Fixed"),
                            ("withholding", "Withholding"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sales", "Sales"),
                            ("purchase", "Purchase"),
                            ("both", "Both"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "recoverable",
                    models.BooleanField(
                        default=False,
                        help_text="Can this tax be reclaimed? (e.g. VAT Input)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "accounting_tax",
            },
        ),
        migrations.CreateModel(
            name="TaxJournalMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "journal_type",
                    models.CharField(
                        choices=[("sales", "Sales"), ("purchase", "Purchase")],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "accounting_tax_journal_map",
            },
        ),
        migrations.CreateModel(
            name="TaxRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Percentage value, e.g. 11.0000",
                        max_digits=7,
                    ),
                ),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "accounting_tax_rate",
                "ordering": ("-effective_from",),
            },
        ),
        migrations.CreateModel(
            name="TaxRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "event",
                    models.CharField(
                        choices=[("sales", "Sales"), ("purchase", "Purchase")],
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=100, help_text="Lower number = higher priority"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "accounting_tax_rule",
                "ordering": ("priority",),
            },
        ),
        migrations.CreateModel(
            name="TaxRuleCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "field",
                    models.CharField(
                        help_text="Context path, e.g. customer.is_taxable",
                        max_length=100,
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            ("eq", "Equals"),
                            ("neq", "Not equals"),
                            ("gt", "Greater than"),
                            ("gte", "Greater than or equal"),
                            ("lt", "Less than"),
                            ("lte", "Less than or equal"),
                            ("in", "In"),
                        ],
                        max_length=10,
                    ),
                ),
                ("value", models.JSONField()),
            ],
            options={
                "db_table": "accounting_tax_rule_condition",
            },
        ),
    ]
