# Generated by Django 5.2.4 on 2026-03-12 02:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("extensions", models.JSONField(blank=True, default=dict)),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Unique partner code per tenant",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(blank=True, max_length=30, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("search_latitude", models.FloatField(db_index=True, null=True)),
                ("search_longitude", models.FloatField(db_index=True, null=True)),
                (
                    "base_price",
                    models.DecimalField(
                        blank=True,
                        db_index=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "rating_avg",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("rating_count", models.PositiveIntegerField(default=0)),
                ("meta", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "business_partners",
                "ordering": ["name"],
            },
        ),
    ]
