# Generated by Django 5.2.4 on 2026-02-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business_partners", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="extensions",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
