# Generated by Django 5.2.4 on 2026-03-26 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business_partners", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerServiceProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "specialization",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("experience_years", models.PositiveIntegerField(default=0)),
                ("bio", models.TextField(blank=True, null=True)),
                (
                    "partner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_profile",
                        to="business_partners.partner",
                    ),
                ),
            ],
        ),
    ]
