# Generated by Django 5.2.4 on 2026-02-21 06:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business_partners", "0003_partner_extensions"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="base_price",
            field=models.DecimalField(
                blank=True, db_index=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="rating_avg",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=4,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="rating_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="partner",
            name="search_latitude",
            field=models.FloatField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="partner",
            name="search_longitude",
            field=models.FloatField(db_index=True, null=True),
        ),
    ]
