# Generated by Django 5.2.4 on 2026-03-26 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("business_partners", "0003_partnerserviceprofile"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="partnerserviceprofile",
            table="business_partners_service_profile",
        ),
    ]
