# Generated by Django 5.2.4 on 2026-03-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business_partners", "0004_alter_partnerserviceprofile_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnerserviceprofile",
            name="working_hours",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='\n        Example:\n        {\n            "start": 8,\n            "end": 18\n        }\n        ',
            ),
        ),
    ]
