# Generated by Django 5.2.4 on 2026-04-11 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business_partners", "0005_partnerserviceprofile_working_hours"),
        ("core_geo_cities", "0001_initial"),
        ("core_geo_countries", "0004_remove_country_uniq_country_tenant_code_and_more"),
        ("core_geo_districts", "0001_initial"),
        (
            "core_geo_regions",
            "0004_remove_region_uniq_region_tenant_country_code_and_more",
        ),
        ("core_geo_villages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="partners",
                to="core_geo_cities.city",
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="partners",
                to="core_geo_countries.country",
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="partners",
                to="core_geo_districts.district",
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="partners",
                to="core_geo_regions.region",
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="village",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="partners",
                to="core_geo_villages.village",
            ),
        ),
    ]
