# core/activity/events/inventory_events.py

"""
Inventory activity event definitions.
"""

from core.activity.constants.events import (
    INVENTORY_ITEM_CREATED,
    INVENTORY_ITEM_UPDATED,
    INVENTORY_PURCHASE_ORDER_APPROVED,
    INVENTORY_PURCHASE_ORDER_CREATED,
    INVENTORY_STOCK_ADJUSTED,
)


class InventoryEvents:

    ITEM_CREATED = INVENTORY_ITEM_CREATED

    ITEM_UPDATED = INVENTORY_ITEM_UPDATED

    STOCK_ADJUSTED = INVENTORY_STOCK_ADJUSTED

    PURCHASE_ORDER_CREATED = INVENTORY_PURCHASE_ORDER_CREATED

    PURCHASE_ORDER_APPROVED = INVENTORY_PURCHASE_ORDER_APPROVED
