# Generated by Django 5.2.4 on 2026-04-21 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core_tenants", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatPresence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_online", models.BooleanField(default=False)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_presence",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "core_chat_presence",
            },
        ),
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("direct", "direct"),
                            ("transactional", "transactional"),
                            ("support", "support"),
                            ("group", "group"),
                        ],
                        default="direct",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "active"),
                            ("archived", "archived"),
                            ("closed", "closed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "context_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("context_id", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="optional title for support/group room",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("last_message", models.TextField(blank=True, null=True)),
                (
                    "last_message_type",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("last_timestamp", models.DateTimeField(blank=True, null=True)),
                ("message_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_chat_rooms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_rooms_last_sender",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_rooms",
                        to="core_tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "core_chat_rooms",
                "ordering": ["-last_timestamp", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "user"),
                            ("partner", "partner"),
                            ("admin", "admin"),
                            ("staff", "staff"),
                        ],
                        default="user",
                        max_length=20,
                    ),
                ),
                ("unread_count", models.PositiveIntegerField(default=0)),
                ("is_muted", models.BooleanField(default=False)),
                ("is_pinned", models.BooleanField(default=False)),
                ("is_archived", models.BooleanField(default=False)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="core_chat.chatroom",
                    ),
                ),
            ],
            options={
                "db_table": "core_chat_participants",
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("text", "text"),
                            ("image", "image"),
                            ("file", "file"),
                            ("audio", "audio"),
                            ("video", "video"),
                            ("system", "system"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(blank=True, default="")),
                ("file", models.FileField(blank=True, null=True, upload_to="chat/")),
                ("file_name", models.CharField(blank=True, max_length=255, null=True)),
                ("file_size", models.PositiveIntegerField(blank=True, null=True)),
                ("mime_type", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "sent"),
                            ("delivered", "delivered"),
                            ("read", "read"),
                        ],
                        default="sent",
                        max_length=20,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True, help_text="future metadata", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "reply_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replies",
                        to="core_chat.chatmessage",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_chat_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="core_chat.chatroom",
                    ),
                ),
            ],
            options={
                "db_table": "core_chat_messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessageRead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("read_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="read_logs",
                        to="core_chat.chatmessage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_read_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "core_chat_message_reads",
                "indexes": [
                    models.Index(
                        fields=["user"], name="core_chat_m_user_id_9054c2_idx"
                    ),
                    models.Index(
                        fields=["message"], name="core_chat_m_message_0c5cbc_idx"
                    ),
                ],
                "unique_together": {("message", "user")},
            },
        ),
        migrations.AddIndex(
            model_name="chatroom",
            index=models.Index(
                fields=["tenant"], name="core_chat_r_tenant__6e7af0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatroom",
            index=models.Index(fields=["type"], name="core_chat_r_type_339b22_idx"),
        ),
        migrations.AddIndex(
            model_name="chatroom",
            index=models.Index(fields=["status"], name="core_chat_r_status_aa73c0_idx"),
        ),
        migrations.AddIndex(
            model_name="chatroom",
            index=models.Index(
                fields=["context_type", "context_id"],
                name="core_chat_r_context_11cdc4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatroom",
            index=models.Index(
                fields=["last_timestamp"], name="core_chat_r_last_ti_225ba8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatroom",
            index=models.Index(
                fields=["is_deleted"], name="core_chat_r_is_dele_97552a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatparticipant",
            index=models.Index(fields=["user"], name="core_chat_p_user_id_4fd6a3_idx"),
        ),
        migrations.AddIndex(
            model_name="chatparticipant",
            index=models.Index(fields=["room"], name="core_chat_p_room_id_212470_idx"),
        ),
        migrations.AddIndex(
            model_name="chatparticipant",
            index=models.Index(
                fields=["user", "is_archived"], name="core_chat_p_user_id_6cf02b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatparticipant",
            index=models.Index(
                fields=["user", "unread_count"], name="core_chat_p_user_id_7aa1b9_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="chatparticipant",
            unique_together={("room", "user")},
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(fields=["room"], name="core_chat_m_room_id_d97bea_idx"),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["sender"], name="core_chat_m_sender__de8ba6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["created_at"], name="core_chat_m_created_c0e964_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["room", "created_at"], name="core_chat_m_room_id_8e98ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(fields=["status"], name="core_chat_m_status_f412bb_idx"),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["is_deleted"], name="core_chat_m_is_dele_94cd7d_idx"
            ),
        ),
    ]
