# Generated by Django 5.2.4 on 2026-04-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="room_key",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
    ]
