# Generated by Django 5.2.4 on 2026-04-21 16:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_chat", "0002_chatroom_room_key"),
        ("core_tenants", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="chatroom",
            constraint=models.UniqueConstraint(
                fields=("room_key",), name="unique_chat_room_key"
            ),
        ),
    ]
