# Generated by Django 5.2.4 on 2026-04-11 01:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core_geo_countries",
            "0003_alter_country_unique_together_alter_country_code_and_more",
        ),
        ("core_geo_regions", "0002_initial"),
        ("core_tenants", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="region",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="region",
            name="center_latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="region",
            name="center_longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="region",
            index=models.Index(
                fields=["tenant", "country"], name="core_region_tenant__3d294b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="region",
            index=models.Index(
                fields=["tenant", "code"], name="core_region_tenant__b80224_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="region",
            index=models.Index(
                fields=["tenant", "name"], name="core_region_tenant__def005_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="region",
            constraint=models.UniqueConstraint(
                fields=("tenant", "country", "code"),
                name="uniq_region_tenant_country_code",
            ),
        ),
    ]
