# Generated by Django 5.2.4 on 2026-04-11 02:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_geo_countries", "0004_remove_country_uniq_country_tenant_code_and_more"),
        (
            "core_geo_regions",
            "0003_alter_region_unique_together_region_center_latitude_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="region",
            name="uniq_region_tenant_country_code",
        ),
        migrations.RemoveIndex(
            model_name="region",
            name="core_region_tenant__3d294b_idx",
        ),
        migrations.RemoveIndex(
            model_name="region",
            name="core_region_tenant__b80224_idx",
        ),
        migrations.RemoveIndex(
            model_name="region",
            name="core_region_tenant__def005_idx",
        ),
        migrations.RemoveField(
            model_name="region",
            name="tenant",
        ),
        migrations.AddConstraint(
            model_name="region",
            constraint=models.UniqueConstraint(
                fields=("country", "code"), name="uniq_region_country_code"
            ),
        ),
    ]
