# verticals/finance/seeds/accounts.py

ACCOUNTS = [
    {
        "code": "1000",
        "name": "Assets",
        "account_type": "asset",
        "normal_balance": "debit",
        "is_group": True,
        "children": [
            {
                "code": "1100",
                "name": "Cash",
                "account_type": "asset",
                "normal_balance": "debit",
                "is_group": False,
            },
            {
                "code": "1110",
                "name": "Bank BCA",
                "account_type": "asset",
                "normal_balance": "debit",
                "is_group": False,
            },
            {
                "code": "1120",
                "name": "Bank Mandiri",
                "account_type": "asset",
                "normal_balance": "debit",
                "is_group": False,
            },
            {
                "code": "1130",
                "name": "Bank BNI",
                "account_type": "asset",
                "normal_balance": "debit",
                "is_group": False,
            },
            {
                "code": "1150",
                "name": "Input Tax",
                "account_type": "asset",
                "normal_balance": "debit",
                "is_group": False,
            },
            {
                "code": "1200",
                "name": "Accounts Receivable",
                "account_type": "asset",
                "normal_balance": "debit",
                "is_group": False,
            },
            {
                "code": "1300",
                "name": "Fixed Assets",
                "account_type": "asset",
                "normal_balance": "debit",
                "is_group": True,
                "children": [
                    {
                        "code": "1310",
                        "name": "Vehicle",
                        "account_type": "asset",
                        "normal_balance": "debit",
                        "is_group": False,
                    },
                    {
                        "code": "1320",
                        "name": "Equipment",
                        "account_type": "asset",
                        "normal_balance": "debit",
                        "is_group": False,
                    },
                    {
                        "code": "1330",
                        "name": "Building",
                        "account_type": "asset",
                        "normal_balance": "debit",
                        "is_group": False,
                    },
                    {
                        "code": "1400",
                        "name": "Accumulated Depreciation",
                        "account_type": "asset",
                        "normal_balance": "credit",
                        "is_group": True,
                        "children": [
                            {
                                "code": "1410",
                                "name": "Accumulated Depreciation - Vehicle",
                                "account_type": "asset",
                                "normal_balance": "credit",
                                "is_group": False,
                            },
                            {
                                "code": "1420",
                                "name": "Accumulated Depreciation - Equipment",
                                "account_type": "asset",
                                "normal_balance": "credit",
                                "is_group": False,
                            },
                            {
                                "code": "1430",
                                "name": "Accumulated Depreciation - Building",
                                "account_type": "asset",
                                "normal_balance": "credit",
                                "is_group": False,
                            },
                        ],
                    },
                ],
            },
        ],
    },
    {
        "code": "2000",
        "name": "Liabilities",
        "account_type": "liability",
        "normal_balance": "credit",
        "is_group": True,
        "children": [
            {
                "code": "2100",
                "name": "Tax Payable",
                "account_type": "liability",
                "normal_balance": "credit",
                "is_group": False,
            },
            {
                "code": "2200",
                "name": "Accounts Payable",
                "account_type": "liability",
                "normal_balance": "credit",
                "is_group": False,
            },
        ],
    },
    {
        "code": "3000",
        "name": "Equity",
        "account_type": "equity",
        "normal_balance": "credit",
        "is_group": True,
    },
    {
        "code": "4000",
        "name": "Revenue",
        "account_type": "revenue",
        "normal_balance": "credit",
        "is_group": True,
        "children": [
            {
                "code": "4100",
                "name": "Sales Revenue",
                "account_type": "revenue",
                "normal_balance": "credit",
                "is_group": False,
            },
            {
                "code": "4200",
                "name": "Gain on Asset Disposal",
                "account_type": "revenue",
                "normal_balance": "credit",
                "is_group": False,
            },
        ],
    },
    {
        "code": "5000",
        "name": "Expenses",
        "account_type": "expense",
        "normal_balance": "debit",
        "is_group": True,
        "children": [
            {
                "code": "5100",
                "name": "Electricity Expense",
                "account_type": "expense",
                "normal_balance": "debit",
                "is_group": False,
            },
            {
                "code": "5200",
                "name": "Internet Expense",
                "account_type": "expense",
                "normal_balance": "debit",
                "is_group": False,
            },
            {
                "code": "5300",
                "name": "Depreciation Expense",
                "account_type": "expense",
                "normal_balance": "debit",
                "is_group": True,
                "children": [
                    {
                        "code": "5310",
                        "name": "Depreciation Expense - Vehicle",
                        "account_type": "expense",
                        "normal_balance": "debit",
                        "is_group": False,
                    },
                    {
                        "code": "5320",
                        "name": "Depreciation Expense - Equipment",
                        "account_type": "expense",
                        "normal_balance": "debit",
                        "is_group": False,
                    },
                    {
                        "code": "5330",
                        "name": "Depreciation Expense - Building",
                        "account_type": "expense",
                        "normal_balance": "debit",
                        "is_group": False,
                    },
                    {
                        "code": "5400",
                        "name": "Loss on Asset Disposal",
                        "account_type": "expense",
                        "normal_balance": "debit",
                        "is_group": False,
                    },
                ],
            },
        ],
    },
]
