# Generated by Django 5.2.4 on 2026-03-12 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reminder_time",
                    models.DurationField(
                        help_text="Time before event to trigger reminder"
                    ),
                ),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("in_app", "In-App"),
                            ("wa", "WhatsApp"),
                        ],
                        default="in_app",
                        max_length=20,
                    ),
                ),
                (
                    "repeat_interval",
                    models.DurationField(
                        blank=True,
                        help_text="Optional repeat interval for reminder",
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "core_schedule_reminders",
                "ordering": ["reminder_time"],
            },
        ),
    ]
