# Generated by Django 5.2.4 on 2026-03-25 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business_partners", "0002_initial"),
        ("business_products", "0002_initial"),
        ("core_tenants", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerOffering",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("duration_minutes", models.PositiveIntegerField(default=60)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "db_table": "business_partner_offerings",
            },
        ),
        migrations.AlterUniqueTogether(
            name="partnerproduct",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="partnerproduct",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="partnerproduct",
            name="partner",
        ),
        migrations.RemoveField(
            model_name="partnerproduct",
            name="product",
        ),
        migrations.RemoveField(
            model_name="partnerproduct",
            name="tenant",
        ),
        migrations.RemoveField(
            model_name="partnerproduct",
            name="updated_by",
        ),
        migrations.AlterUniqueTogether(
            name="product",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[("good", "Good"), ("service", "Service")],
                db_index=True,
                default="good",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["tenant", "product_type"], name="business_pr_tenant__13edca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["tenant", "is_active"], name="business_pr_tenant__43ea10_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                condition=models.Q(("code", None), _negated=True),
                fields=("tenant", "code"),
                name="unique_product_code_per_tenant",
            ),
        ),
        migrations.AddField(
            model_name="partneroffering",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="partneroffering",
            name="partner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offerings",
                to="business_partners.partner",
            ),
        ),
        migrations.AddField(
            model_name="partneroffering",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offerings",
                to="business_products.product",
            ),
        ),
        migrations.AddField(
            model_name="partneroffering",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="core_tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="partneroffering",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="PartnerProduct",
        ),
        migrations.AddIndex(
            model_name="partneroffering",
            index=models.Index(
                fields=["tenant", "partner"], name="business_pa_tenant__c66fc3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partneroffering",
            index=models.Index(
                fields=["tenant", "is_active"], name="business_pa_tenant__a08d0b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="partneroffering",
            unique_together={("tenant", "partner", "product")},
        ),
    ]
