# Generated by Django 5.2.4 on 2026-04-05 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_account", "0003_initial"),
        ("marketplace", "0003_order_completed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="core_account.useraddress",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="address_snapshot",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="fulfillment_type",
            field=models.CharField(
                choices=[
                    ("delivery", "Delivery"),
                    ("on_site", "On Site"),
                    ("pickup", "Pickup"),
                    ("online", "Online"),
                ],
                default="on_site",
                max_length=20,
            ),
        ),
    ]
