# Generated by Django 5.2.4 on 2026-04-05 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business_partners", "0005_partnerserviceprofile_working_hours"),
        ("marketplace", "0004_order_address_order_address_snapshot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_orders",
                to="business_partners.partner",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="selected_partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="selected_orders",
                to="business_partners.partner",
            ),
        ),
    ]
