# Generated by Django 5.2.4 on 2026-04-10 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_classifications_categories", "0002_initial"),
        ("marketplace", "0007_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketplaceproduct",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="marketplace_products",
                to="core_classifications_categories.category",
            ),
        ),
    ]
