# Generated by Django 5.2.4 on 2026-04-13 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0008_marketplaceproduct_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="rejected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="rejected_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
