# Generated by Django 5.2.4 on 2026-04-13 06:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0009_order_rejected_at_order_rejected_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="subtotal_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="total_fee_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
    ]
