NOTIFICATION_TYPE_SYSTEM = "system"
NOTIFICATION_TYPE_INFO = "info"
NOTIFICATION_TYPE_WARNING = "warning"
NOTIFICATION_TYPE_ERROR = "error"

NOTIFICATION_TYPES = [
    NOTIFICATION_TYPE_SYSTEM,
    NOTIFICATION_TYPE_INFO,
    NOTIFICATION_TYPE_WARNING,
    NOTIFICATION_TYPE_ERROR,
]
