# Generated by Django 5.2.4 on 2026-02-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "business_bookings",
            "0002_rename_base_price_booking_subtotal_amount_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="is_financial_locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="booking",
            name="payment_expired_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
