# Generated by Django 5.2.4 on 2026-02-27 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business_bookings", "0003_booking_is_financial_locked_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="partner_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
