# Generated by Django 5.2.4 on 2026-02-27 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business_bookings", "0004_booking_partner_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="partner_amount",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
