# Generated by Django 5.2.4 on 2026-03-12 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Journal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("journal_number", models.CharField(max_length=50, unique=True)),
                (
                    "journal_type",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General"),
                            ("SALES", "Sales"),
                            ("PURCHASE", "Purchase"),
                            ("PAYMENT", "Payment"),
                            ("PAYROLL", "Payroll"),
                            ("INVENTORY", "Inventory"),
                            ("ADJUSTMENT", "Adjustment"),
                            ("OPENING", "Opening Balance"),
                            ("CLOSING", "Closing"),
                        ],
                        max_length=20,
                    ),
                ),
                ("journal_date", models.DateField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "source_app",
                    models.CharField(
                        blank=True,
                        help_text="Origin module (transactions, payroll, inventory, etc)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        blank=True,
                        help_text="UUID / ID from source module",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("POSTED", "Posted"),
                            ("REVERSED", "Reversed"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "is_manual",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates this journal was created manually (adjustment)",
                    ),
                ),
            ],
            options={
                "db_table": "accounting_journals",
                "ordering": ["-journal_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="JournalLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "debit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "credit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("memo", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "accounting_journal_lines",
            },
        ),
    ]
