# Generated by Django 5.2.4 on 2026-02-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting_journals", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="is_manual",
            field=models.BooleanField(
                default=False,
                help_text="Indicates this journal was created manually (adjustment)",
            ),
        ),
    ]
