# Generated by Django 5.2.4 on 2026-03-12 02:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        help_text="Generated document number",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="External or manual reference",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("issued", "Issued"),
                            ("void", "Void"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(help_text="Date when document is issued"),
                ),
                (
                    "issued_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when document is legally issued",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "source_type",
                    models.CharField(
                        blank=True,
                        help_text="Source domain (e.g. SALES_ORDER, PURCHASE_ORDER)",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("source_id", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "subtotal_amount",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "adjustment_amount",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Discount, rounding, etc",
                        max_digits=18,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
            ],
            options={
                "db_table": "business_documents",
                "ordering": ["-issue_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "label",
                    models.CharField(
                        help_text="Human readable line description", max_length=255
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("1.0000"), max_digits=14
                    ),
                ),
                ("unit_price", models.DecimalField(decimal_places=4, max_digits=16)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="quantity × unit_price (stored, not computed)",
                        max_digits=18,
                    ),
                ),
                (
                    "meta",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Optional metadata (e.g. product_id, service_ref)",
                    ),
                ),
            ],
            options={
                "db_table": "business_document_lines",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Unique document type code (e.g. INVOICE, RECEIPT)",
                        max_length=50,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Human readable name", max_length=100),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "business_document_types",
                "ordering": ["name"],
            },
        ),
    ]
