# Generated by Django 5.2.4 on 2026-01-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        help_text="Generated document number",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="External or manual reference",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("issued", "Issued"),
                            ("void", "Void"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(help_text="Date when document is issued"),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "source_type",
                    models.CharField(
                        blank=True,
                        help_text="Source domain (e.g. SALES_ORDER, PURCHASE_ORDER)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "source_id",
                    models.PositiveIntegerField(
                        blank=True, help_text="ID of source object", null=True
                    ),
                ),
            ],
            options={
                "db_table": "business_documents",
                "ordering": ["-issue_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Unique document type code (e.g. INVOICE, RECEIPT)",
                        max_length=50,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Human readable name", max_length=100),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "business_document_types",
                "ordering": ["name"],
            },
        ),
    ]
