# Generated by Django 5.2.4 on 2026-02-07 04:50

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business_documents", "0002_initial"),
        ("core_tenants", "0003_tenant_branding"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="adjustment_amount",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text="Discount, rounding, etc",
                max_digits=18,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="issued_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when document is legally issued",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="subtotal_amount",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="document",
            name="total_amount",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="document",
            name="source_id",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="document",
            name="source_type",
            field=models.CharField(
                blank=True,
                help_text="Source domain (e.g. SALES_ORDER, PURCHASE_ORDER)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="DocumentLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "label",
                    models.CharField(
                        help_text="Human readable line description", max_length=255
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("1.0000"), max_digits=14
                    ),
                ),
                ("unit_price", models.DecimalField(decimal_places=4, max_digits=16)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="quantity × unit_price (stored, not computed)",
                        max_digits=18,
                    ),
                ),
                (
                    "meta",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Optional metadata (e.g. product_id, service_ref)",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="business_documents.document",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core_tenants.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "business_document_lines",
                "ordering": ["id"],
            },
        ),
    ]
