# Generated by Django 5.2.4 on 2026-02-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "business_documents",
            "0003_document_adjustment_amount_document_issued_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="source_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
