# Generated by Django 5.2.4 on 2026-02-05 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business_customers", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="extensions",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
