# Generated by Django 5.2.4 on 2026-02-11 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core_tenants", "0003_tenant_branding"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(
                        help_text="Stored file path (handled by storage service)",
                        upload_to="uploads/",
                    ),
                ),
                (
                    "original_name",
                    models.CharField(
                        help_text="Original filename from user", max_length=255
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(help_text="Detected MIME type", max_length=100),
                ),
                ("size", models.BigIntegerField(help_text="File size in bytes")),
                (
                    "related_entity",
                    models.CharField(
                        help_text="Target entity key (e.g. products, invoices)",
                        max_length=100,
                    ),
                ),
                ("related_id", models.UUIDField(help_text="Target entity ID")),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="Publicly accessible file"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core_tenants.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "core_files",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "related_entity", "related_id"],
                        name="core_files_tenant__9b7a9a_idx",
                    )
                ],
            },
        ),
    ]
