# Generated by Django 5.2.4 on 2026-03-12 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(
                        help_text="Stored file path (handled by storage service)",
                        upload_to="uploads/",
                    ),
                ),
                (
                    "original_name",
                    models.CharField(
                        help_text="Original filename from user", max_length=255
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(help_text="Detected MIME type", max_length=100),
                ),
                ("size", models.BigIntegerField(help_text="File size in bytes")),
                (
                    "related_entity",
                    models.CharField(
                        help_text="Target entity key (e.g. products, invoices)",
                        max_length=100,
                    ),
                ),
                ("related_id", models.CharField(max_length=64)),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="Publicly accessible file"
                    ),
                ),
            ],
            options={
                "db_table": "core_files",
                "ordering": ["-created_at"],
            },
        ),
    ]
