# Generated by Django 5.2.4 on 2026-02-11 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_files", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="related_id",
            field=models.CharField(max_length=64),
        ),
    ]
