# Generated by Django 5.2.4 on 2026-04-29 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_files", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(
                help_text="Stored file path (handled by storage service)",
                max_length=500,
                upload_to="uploads/",
            ),
        ),
    ]
