# Generated by Django 5.2.4 on 2026-01-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        help_text="External reference (bank slip, gateway ref, etc)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("IN", "Incoming"), ("OUT", "Outgoing")], max_length=3
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("currency", models.CharField(default="IDR", max_length=10)),
                (
                    "method",
                    models.CharField(
                        help_text="cash, transfer, qris, gateway, etc", max_length=50
                    ),
                ),
                ("payment_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("POSTED", "Posted"),
                            ("VOID", "Void"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "document_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Referenced document (invoice, bill, etc)",
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "business_payments",
                "ordering": ["-payment_date", "-id"],
            },
        ),
    ]
