# Generated by Django 5.2.4 on 2026-01-22 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core_users", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="user",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="user",
            name="tenant",
        ),
    ]
