# Generated by Django 5.2.4 on 2026-02-17 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_files", "0002_alter_file_related_id"),
        ("core_users", "0003_user_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_avatars",
                to="core_files.file",
            ),
        ),
    ]
