"""
Django settings for atzee_backend project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
from dotenv import load_dotenv
from corsheaders.defaults import default_headers

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(os.path.join(BASE_DIR, ".env"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "dummy-fallback")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True"

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "").split(",")


# Application definition

DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

CORE_APPS = [
    "core.apps.CoreConfig",
    "core.users.apps.UsersConfig",
    "core.tenants.apps.TenantsConfig",
    "core.roles.apps.RolesConfig",
    "core.permissions.apps.PermissionsConfig",
    "core.ui.apps.UIConfig",
    "core.settings.apps.SettingsConfig",
    "core.audit_logs.apps.AuditLogsConfig",
    "core.notifications.apps.NotificationsConfig",
    "core.entities.apps.EntitiesConfig",
    "core.dashboard.apps.DashboardConfig",
]

BUSINESS_APPS = [
    "business.customers.apps.CustomersConfig",
    "business.products.apps.ProductsConfig",
    "business.inventory.apps.InventoryConfig",
    "business.partners.apps.PartnersConfig",
    "business.transactions.apps.TransactionsConfig",
    "business.documents.apps.DocumentsConfig",
    "business.payments.apps.PaymentsConfig",
]

ACCOUNTING_APPS = [
    "accounting.chart_of_accounts.apps.ChartOfAccountsConfig",
    "accounting.journals.apps.JournalsConfig",
    "accounting.ledger.apps.LedgerConfig",
    "accounting.financial_reports.apps.FinancialReportsConfig",
    "accounting.fiscal_period.apps.FiscalPeriodConfig",
    "accounting.taxes.apps.TaxesConfig",
]

HR_APPS = [
    "hr.employees.apps.EmployeesConfig",
    "hr.attendance.apps.AttendanceConfig",
    "hr.payroll.apps.PayrollConfig",
]

VERTICAL_APPS = [
    "verticals.apotek.apps.ApotekConfig",
]

INSTALLED_APPS = (
    ["corsheaders"] 
    +
    DJANGO_APPS 
    + [
        "rest_framework",
        "rest_framework.authtoken",
    ]
    + CORE_APPS 
    + BUSINESS_APPS 
    + ACCOUNTING_APPS 
    + HR_APPS
    + VERTICAL_APPS
    + ["setup"]
)

MIDDLEWARE = [
    # CORS & SECURITY
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",

    # SESSION & REQUEST
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",

    # AUTH DJANGO (WAJIB sebelum custom middleware)
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",

    # CORE CONTEXT (SETELAH USER TER-RESOLVE)
    "core.tenants.middleware.TenantContextMiddleware",
    "core.permissions.middleware.PermissionGuardMiddleware",

    # AUDIT PALING AKHIR
    "core.audit_logs.middleware.AuditMiddleware"
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "EXCEPTION_HANDLER": "shared.utils.exceptions.core_exception_handler"
}

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

AUTH_USER_MODEL = "core_users.User"

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv("DB_NAME"),
        'USER': os.getenv("DB_USER"),
        'PASSWORD': os.getenv("DB_PASSWORD"),
        'HOST': os.getenv("DB_HOST", "localhost"),
        'PORT': os.getenv("DB_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:5173",
    "http://localhost:5174",
    "https://accounting.atzee.web.id",
    "https://onecore.atzee.web.id",
]

CORS_ALLOW_HEADERS = list(default_headers) + [
    "content-type",
    "x-api-key",
    "x-oid",
    "x-uid",
    "x-app",
    "x-puid",
    "x-tenant-id",
]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = False  # tetap aman

SERVICE_API_KEY = os.getenv("SERVICE_API_KEY")

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    # ...
}



# CACHE (DEVELOPMENT)
# ================================================================
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
    }
}

# CACHE (PRODUCTION)
# ================================================================
# CACHES = {
#     "default": {
#         "BACKEND": "django_redis.cache.RedisCache",
#         "LOCATION": "redis://127.0.0.1:6379/1",
#         "OPTIONS": {
#             "CLIENT_CLASS": "django_redis.client.DefaultClient",
#         }
#     }
# }
