# Generated by Django 5.2.4 on 2026-03-12 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core_permissions", "0001_initial"),
        ("core_roles", "0001_initial"),
        ("core_tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="permission",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="permissions",
                to="core_tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="rolepermission",
            name="permission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="permission_roles",
                to="core_permissions.permission",
            ),
        ),
        migrations.AddField(
            model_name="rolepermission",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_permissions",
                to="core_roles.role",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="permission",
            unique_together={("tenant", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="rolepermission",
            unique_together={("role", "permission")},
        ),
    ]
