# Generated by Django 5.2.4 on 2026-02-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_permissions", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="permission",
            name="module",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
