# Generated by Django 5.2.4 on 2026-03-12 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounting_journals", "0002_initial"),
        ("accounting_ledger", "0001_initial"),
        ("core_tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ledgerentry",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ledgerentry",
            name="journal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ledger_entries",
                to="accounting_journals.journal",
            ),
        ),
        migrations.AddField(
            model_name="ledgerentry",
            name="journal_line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="accounting_journals.journalline",
            ),
        ),
        migrations.AddField(
            model_name="ledgerentry",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="core_tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="ledgerentry",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="ledgerentry",
            index=models.Index(
                fields=["tenant", "account", "entry_date"],
                name="accounting__tenant__b7e8b1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ledgerentry",
            index=models.Index(
                fields=["tenant", "journal"], name="accounting__tenant__37ad5a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="ledgerentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("credit__gt", 0), ("debit", 0)),
                    models.Q(("credit", 0), ("debit__gt", 0)),
                    _connector="OR",
                ),
                name="ledger_debit_xor_credit",
            ),
        ),
    ]
