# Generated by Django 5.2.4 on 2026-02-07 04:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting_chart_of_accounts", "0002_initial"),
        ("accounting_journals", "0002_initial"),
        ("accounting_ledger", "0002_initial"),
        ("core_tenants", "0003_tenant_branding"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ledgerentry",
            name="account_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="ledgerentry",
            name="account_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="ledgerentry",
            name="balance_direction",
            field=models.CharField(
                choices=[("DEBIT", "Debit"), ("CREDIT", "Credit")],
                help_text="Denormalized for reporting performance",
                max_length=6,
            ),
        ),
        migrations.AddIndex(
            model_name="ledgerentry",
            index=models.Index(
                fields=["tenant", "journal"], name="accounting__tenant__37ad5a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="ledgerentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("credit__gt", 0), ("debit", 0)),
                    models.Q(("credit", 0), ("debit__gt", 0)),
                    _connector="OR",
                ),
                name="ledger_debit_xor_credit",
            ),
        ),
    ]
