# Generated by Django 5.2.4 on 2026-05-29 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_classifications_categories", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="color",
            field=models.CharField(
                blank=True,
                help_text="Hex color, e.g. #10B981",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="icon_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
