# Generated by Django 5.2.4 on 2026-03-12 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core_tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UIPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=150, unique=True)),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True, null=True)),
                ("domain", models.CharField(max_length=100)),
                ("entity", models.CharField(max_length=100)),
                ("path", models.CharField(blank=True, max_length=200, null=True)),
                ("permissions", models.JSONField(default=list)),
                ("blocks", models.JSONField(default=list)),
                (
                    "data_source",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("method", models.CharField(blank=True, max_length=20, null=True)),
                ("accept_context", models.BooleanField(default=True)),
                (
                    "payload_from_context",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="TenantNavigationConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("sidebar", "Sidebar"),
                            ("bottom", "Bottom Navigation"),
                            ("drawer", "Drawer"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "device",
                    models.CharField(
                        choices=[
                            ("mobile", "Mobile"),
                            ("desktop", "Desktop"),
                            ("all", "All Devices"),
                        ],
                        default="all",
                        max_length=20,
                    ),
                ),
                ("app", models.CharField(blank=True, max_length=100, null=True)),
                ("role", models.CharField(blank=True, max_length=50, null=True)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="navigation_configs",
                        to="core_tenants.tenant",
                    ),
                ),
            ],
            options={
                "unique_together": {("tenant", "type", "device", "app", "role")},
            },
        ),
        migrations.CreateModel(
            name="UIMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("label", models.CharField(max_length=100)),
                ("icon", models.CharField(blank=True, max_length=50, null=True)),
                ("app", models.CharField(max_length=100)),
                ("resource", models.CharField(max_length=100)),
                ("action", models.CharField(max_length=50)),
                ("route", models.CharField(max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="core_ui.uimenu",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="TenantNavigationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("menu", "Menu"),
                            ("page", "Page"),
                            ("entity", "Entity"),
                            ("workflow", "Workflow"),
                            ("custom", "Custom Route"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        help_text="Page key, entity key, workflow key, or route",
                        max_length=150,
                    ),
                ),
                (
                    "label_override",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "icon_override",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "route_override",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "badge_source",
                    models.CharField(
                        blank=True,
                        help_text="Entity key or service key for badge counter",
                        max_length=150,
                        null=True,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "navigation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core_ui.tenantnavigationconfig",
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core_ui.uimenu",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
