# Generated by Django 5.2.4 on 2026-01-21 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UIMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("label", models.CharField(max_length=100)),
                ("icon", models.CharField(blank=True, max_length=50, null=True)),
                ("app", models.CharField(max_length=100)),
                ("resource", models.CharField(max_length=100)),
                ("action", models.CharField(max_length=50)),
                ("route", models.CharField(max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="core_ui.uimenu",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
