# Generated by Django 5.2.4 on 2026-01-24 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_ui", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UIPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("title", models.CharField(max_length=100)),
                (
                    "layout",
                    models.CharField(
                        choices=[
                            ("table", "Table"),
                            ("detail", "Detail"),
                            ("dashboard", "Dashboard"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "data_source",
                    models.CharField(
                        help_text="API endpoint used by frontend", max_length=200
                    ),
                ),
                ("app", models.CharField(max_length=100)),
                ("resource", models.CharField(max_length=100)),
                ("action", models.CharField(default="view", max_length=50)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "UI Page",
                "verbose_name_plural": "UI Pages",
            },
        ),
        migrations.CreateModel(
            name="UIPageColumn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100)),
                ("label", models.CharField(max_length=100)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="columns",
                        to="core_ui.uipage",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
