# Generated by Django 5.2.4 on 2026-04-13 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_ui", "0002_uipage_meta"),
    ]

    operations = [
        migrations.AddField(
            model_name="uipage",
            name="subtitle",
            field=models.TextField(blank=True, null=True),
        ),
    ]
