# Generated by Django 5.2.4 on 2026-01-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_ui", "0002_uipage_uipagecolumn"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="uipage",
            options={"ordering": ["key"]},
        ),
        migrations.RemoveField(
            model_name="uipage",
            name="action",
        ),
        migrations.RemoveField(
            model_name="uipage",
            name="app",
        ),
        migrations.RemoveField(
            model_name="uipage",
            name="data_source",
        ),
        migrations.RemoveField(
            model_name="uipage",
            name="layout",
        ),
        migrations.RemoveField(
            model_name="uipage",
            name="resource",
        ),
        migrations.AddField(
            model_name="uipage",
            name="blocks",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="uipage",
            name="entity",
            field=models.CharField(default="system", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="uipage",
            name="permissions",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="uipage",
            name="key",
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name="uipage",
            name="title",
            field=models.CharField(max_length=150),
        ),
        migrations.DeleteModel(
            name="UIPageColumn",
        ),
    ]
