# Generated by Django 5.2.4 on 2026-05-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_ui", "0003_uipage_subtitle"),
    ]

    operations = [
        migrations.AddField(
            model_name="uipage",
            name="actions",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
