# Generated by Django 5.2.4 on 2026-01-28 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_ui", "0003_alter_uipage_options_remove_uipage_action_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="uipage",
            name="domain",
            field=models.CharField(default="business", max_length=100),
            preserve_default=False,
        ),
    ]
