# Generated by Django 5.2.4 on 2026-02-01 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_ui", "0004_uipage_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="uipage",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
