# Generated by Django 5.2.4 on 2026-02-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_ui", "0005_uipage_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="uimenu",
            name="page_key",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
