# Generated by Django 5.2.4 on 2026-02-05 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core_ui", "0006_uimenu_page_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uimenu",
            name="page_key",
        ),
    ]
