# Generated by Django 5.2.4 on 2026-02-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_ui", "0007_remove_uimenu_page_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="uipage",
            name="path",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
