# Generated by Django 5.2.4 on 2026-02-12 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_tenants", "0003_tenant_branding"),
        ("core_ui", "0008_uipage_path"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantNavigationConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("sidebar", "Sidebar"),
                            ("bottom", "Bottom Navigation"),
                            ("drawer", "Drawer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("app", models.CharField(blank=True, max_length=100, null=True)),
                ("role", models.CharField(blank=True, max_length=50, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="navigation_configs",
                        to="core_tenants.tenant",
                    ),
                ),
            ],
            options={
                "unique_together": {("tenant", "type", "app", "role")},
            },
        ),
        migrations.CreateModel(
            name="TenantNavigationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core_ui.uimenu"
                    ),
                ),
                (
                    "navigation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core_ui.tenantnavigationconfig",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
