# Generated by Django 5.2.4 on 2026-02-12 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_tenants", "0003_tenant_branding"),
        ("core_ui", "0009_tenantnavigationconfig_tenantnavigationitem"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tenantnavigationconfig",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="tenantnavigationconfig",
            name="device",
            field=models.CharField(
                choices=[
                    ("mobile", "Mobile"),
                    ("desktop", "Desktop"),
                    ("all", "All Devices"),
                ],
                default="all",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tenantnavigationconfig",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tenantnavigationitem",
            name="action_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("menu", "Menu"),
                    ("page", "Page"),
                    ("entity", "Entity"),
                    ("workflow", "Workflow"),
                    ("custom", "Custom Route"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tenantnavigationitem",
            name="badge_source",
            field=models.CharField(
                blank=True,
                help_text="Entity key or service key for badge counter",
                max_length=150,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tenantnavigationitem",
            name="icon_override",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="tenantnavigationitem",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="tenantnavigationitem",
            name="is_primary",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tenantnavigationitem",
            name="label_override",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="tenantnavigationitem",
            name="route_override",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="tenantnavigationitem",
            name="target",
            field=models.CharField(
                blank=True,
                help_text="Page key, entity key, workflow key, or route",
                max_length=150,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tenantnavigationitem",
            name="menu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core_ui.uimenu",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tenantnavigationconfig",
            unique_together={("tenant", "type", "device", "app", "role")},
        ),
    ]
