# Generated by Django 5.2.4 on 2026-02-12 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_ui", "0010_alter_tenantnavigationconfig_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantnavigationitem",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("menu", "Menu"),
                    ("page", "Page"),
                    ("entity", "Entity"),
                    ("workflow", "Workflow"),
                    ("custom", "Custom Route"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tenantnavigationitem",
            name="target",
            field=models.CharField(
                help_text="Page key, entity key, workflow key, or route", max_length=150
            ),
        ),
    ]
