# Generated by Django 5.2.4 on 2026-02-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_ui", "0011_alter_tenantnavigationitem_action_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="uipage",
            name="data_source",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
