# Generated by Django 5.2.4 on 2026-02-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_ui", "0012_uipage_data_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="uipage",
            name="accept_context",
            field=models.BooleanField(default=True),
        ),
    ]
