# Generated by Django 5.2.4 on 2026-02-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_ui", "0013_uipage_accept_context"),
    ]

    operations = [
        migrations.AddField(
            model_name="uipage",
            name="method",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
