# Generated by Django 5.2.4 on 2026-02-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_ui", "0014_uipage_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="uipage",
            name="payload_from_context",
            field=models.JSONField(default=list),
        ),
    ]
