# Generated by Django 5.2.4 on 2026-02-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_ui", "0015_uipage_payload_from_context"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uipage",
            name="payload_from_context",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
