# Generated by Django 5.2.4 on 2026-04-11 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core_geo_cities", "0001_initial"),
        ("core_geo_countries", "0004_remove_country_uniq_country_tenant_code_and_more"),
        ("core_geo_districts", "0001_initial"),
        (
            "core_geo_regions",
            "0004_remove_region_uniq_region_tenant_country_code_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Village",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=100)),
                ("center_latitude", models.FloatField(blank=True, null=True)),
                ("center_longitude", models.FloatField(blank=True, null=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="villages",
                        to="core_geo_cities.city",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="villages",
                        to="core_geo_countries.country",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="villages",
                        to="core_geo_districts.district",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="villages",
                        to="core_geo_regions.region",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "core_villages",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["country", "region", "city", "district"],
                        name="core_villag_country_2624a1_idx",
                    ),
                    models.Index(fields=["code"], name="core_villag_code_1ce064_idx"),
                    models.Index(fields=["name"], name="core_villag_name_814659_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("district", "code"), name="uniq_village_district_code"
                    )
                ],
            },
        ),
    ]
