# verticals/pos/seeds/partners.py

PARTNERS = [
    {
        "code": "SUP001",
        "name": "PT Sumber Makmur Abadi",
        "email": "sales@sumbermakmur.co.id",
        "phone": "021-55667788",
        "address": "Jl. Industri Raya No. 12, Jakarta Barat",
        "latitude": -6.1683,
        "longitude": 106.7588,
        "base_price": 0,
        "rating_avg": 4.7,
        "rating_count": 152,
        "image": "supplier1.jpg",
    },
    {
        "code": "SUP002",
        "name": "CV Nusantara Beverage",
        "email": "order@nusantarabev.co.id",
        "phone": "021-44556677",
        "address": "Jl. Raya Bekasi KM 21, Bekasi",
        "latitude": -6.2383,
        "longitude": 106.9756,
        "base_price": 0,
        "rating_avg": 4.5,
        "rating_count": 98,
        "image": "supplier2.jpg",
    },
    {
        "code": "SUP003",
        "name": "PT Fresh Indo Sejahtera",
        "email": "cs@freshindo.co.id",
        "phone": "021-77889900",
        "address": "Jl. Raya Bogor No. 45, Depok",
        "latitude": -6.4025,
        "longitude": 106.7942,
        "base_price": 0,
        "rating_avg": 4.8,
        "rating_count": 201,
        "image": "supplier3.jpg",
    },
    {
        "code": "SUP004",
        "name": "CV Sinar Stationery",
        "email": "admin@sinarstationery.co.id",
        "phone": "021-66778899",
        "address": "Jl. Mangga Dua No. 88, Jakarta Utara",
        "latitude": -6.1200,
        "longitude": 106.8681,
        "base_price": 0,
        "rating_avg": 4.6,
        "rating_count": 76,
        "image": "supplier4.jpg",
    },
    {
        "code": "SUP005",
        "name": "PT Global Trading Sentosa",
        "email": "info@globaltrading.co.id",
        "phone": "021-33445566",
        "address": "Jl. Serpong Raya No. 10, Tangerang Selatan",
        "latitude": -6.3025,
        "longitude": 106.7210,
        "base_price": 0,
        "rating_avg": 4.4,
        "rating_count": 63,
        "image": "supplier5.jpg",
    },
]