# Generated by Django 5.2.4 on 2026-02-09 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core_classifications_tags", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="tag",
            table="core_tags",
        ),
    ]
