# Generated by Django 5.2.4 on 2026-02-11 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core_classifications_tags", "0002_alter_tag_table"),
        ("core_tenants", "0003_tenant_branding"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TagRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("object_id", models.PositiveBigIntegerField()),
            ],
            options={
                "db_table": "core_tag_relations",
            },
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(
                fields=["tenant", "code"], name="core_tags_tenant__aa1e72_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(
                fields=["tenant", "name"], name="core_tags_tenant__0f9e4b_idx"
            ),
        ),
        migrations.AddField(
            model_name="tagrelation",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="tagrelation",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tagrelation",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relations",
                to="core_classifications_tags.tag",
            ),
        ),
        migrations.AddField(
            model_name="tagrelation",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="core_tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="tagrelation",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="tagrelation",
            index=models.Index(
                fields=["tenant", "content_type", "object_id"],
                name="core_tag_re_tenant__79d628_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tagrelation",
            index=models.Index(
                fields=["tenant", "tag"], name="core_tag_re_tenant__29380f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tagrelation",
            index=models.Index(
                fields=["tenant", "content_type", "tag"],
                name="core_tag_re_tenant__74414b_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tagrelation",
            unique_together={("tenant", "tag", "content_type", "object_id")},
        ),
    ]
