# Generated by Django 5.2.4 on 2026-03-12 02:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("branding", models.JSONField(blank=True, default=dict)),
                (
                    "platform_fee_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "vertical",
                    models.CharField(
                        choices=[
                            ("core", "Core Platform"),
                            ("ustadzku", "Ustadzku"),
                            ("clinic", "Clinic"),
                            ("school", "School"),
                        ],
                        db_index=True,
                        default="core",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "core_tenants",
            },
        ),
        migrations.CreateModel(
            name="UserTenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_memberships",
                        to="core_tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "core_user_tenants",
            },
        ),
    ]
