# Generated by Django 5.2.4 on 2026-01-23 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_tenants", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="branding",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
