# Generated by Django 5.2.4 on 2026-02-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_tenants", "0003_tenant_branding"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="vertical",
            field=models.CharField(
                choices=[
                    ("core", "Core Platform"),
                    ("ustadzku", "Ustadzku"),
                    ("clinic", "Clinic"),
                    ("school", "School"),
                ],
                db_index=True,
                default="core",
                max_length=50,
            ),
        ),
    ]
