# Generated by Django 5.2.4 on 2026-02-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_tenants", "0004_tenant_vertical"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="platform_fee_percent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
