# Generated by Django 5.2.4 on 2026-03-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business_booking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="resource_id",
            field=models.CharField(max_length=50),
        ),
    ]
