# Generated by Django 5.2.4 on 2026-03-30 07:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business_booking", "0002_alter_booking_resource_id"),
        ("core_tenants", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="order_item_id",
            new_name="order_id",
        ),
        migrations.AddField(
            model_name="booking",
            name="total_duration",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["tenant", "resource_type", "resource_id", "start_time"],
                name="business_bo_tenant__a3d605_idx",
            ),
        ),
    ]
