# Generated by Django 5.2.4 on 2026-03-12 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING", "Pending"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        help_text="Transaction ID from payment gateway",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "gateway_response",
                    models.JSONField(
                        blank=True,
                        help_text="Raw response from payment gateway",
                        null=True,
                    ),
                ),
                (
                    "client_payload",
                    models.JSONField(
                        blank=True,
                        help_text="Data needed by frontend (redirect_url, snap_token, qr_string, etc)",
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "core_payments",
            },
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "gateway",
                    models.CharField(
                        choices=[
                            ("WALLET", "Internal Wallet"),
                            ("MIDTRANS", "Midtrans"),
                            ("XENDIT", "Xendit"),
                        ],
                        default="WALLET",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "core_payment_methods",
            },
        ),
    ]
