# Generated by Django 5.2.4 on 2026-02-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_payment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="external_id",
            field=models.CharField(
                blank=True,
                help_text="Transaction ID from payment gateway",
                max_length=150,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="gateway_response",
            field=models.JSONField(
                blank=True, help_text="Raw response from payment gateway", null=True
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="gateway",
            field=models.CharField(
                choices=[
                    ("WALLET", "Internal Wallet"),
                    ("MIDTRANS", "Midtrans"),
                    ("XENDIT", "Xendit"),
                ],
                default="WALLET",
                max_length=20,
            ),
        ),
    ]
