# Generated by Django 5.2.4 on 2026-02-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_payment", "0002_payment_external_id_payment_gateway_response_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="client_payload",
            field=models.JSONField(
                blank=True,
                help_text="Data needed by frontend (redirect_url, snap_token, qr_string, etc)",
                null=True,
            ),
        ),
    ]
