# Generated by Django 5.2.4 on 2026-03-12 02:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OTPCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("phone", models.CharField(max_length=20)),
                ("code", models.CharField(max_length=128)),
                ("expired_at", models.DateTimeField()),
                ("attempts", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "core_otp_code",
                "ordering": ["-created_at"],
            },
        ),
    ]
