# Generated by Django 5.2.4 on 2026-02-03 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business_inventory", "0002_initial"),
        ("business_product", "0002_initial"),
        ("core_tenants", "0003_tenant_branding"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryLot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("lot_code", models.CharField(max_length=64)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("manufacture_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_lots",
                        to="business_product.product",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core_tenants.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "business_inventory_lots",
            },
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="lot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_movements",
                to="business_inventory.inventorylot",
            ),
        ),
        migrations.AddIndex(
            model_name="inventorylot",
            index=models.Index(
                fields=["tenant", "product"], name="business_in_tenant__ee3ec8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventorylot",
            index=models.Index(
                fields=["tenant", "expiry_date"], name="business_in_tenant__0cd9e6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="inventorylot",
            unique_together={("tenant", "product", "lot_code")},
        ),
    ]
