# Generated by Django 5.2.4 on 2026-04-13 05:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "business_partners",
            "0006_partner_city_partner_country_partner_district_and_more",
        ),
        ("core_classifications_categories", "0002_initial"),
        ("core_tenants", "0002_initial"),
        ("marketplace", "0009_order_rejected_at_order_rejected_reason"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeeConfig",
            fields=[
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "fee_type",
                    models.CharField(
                        choices=[("percent", "Percent"), ("fixed", "Fixed")],
                        max_length=20,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percent (0-100) atau nominal fixed",
                        max_digits=10,
                    ),
                ),
                (
                    "applies_to",
                    models.CharField(
                        choices=[("customer", "Customer"), ("partner", "Partner")],
                        max_length=20,
                    ),
                ),
                (
                    "min_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "max_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fee_configs",
                        to="core_classifications_categories.category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fee_configs",
                        to="business_partners.partner",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core_tenants.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "core_fee_configs",
                "indexes": [
                    models.Index(
                        fields=["tenant", "is_active"],
                        name="core_fee_co_tenant__c5c7e0_idx",
                    ),
                    models.Index(
                        fields=["tenant", "category"],
                        name="core_fee_co_tenant__fdb06b_idx",
                    ),
                    models.Index(
                        fields=["tenant", "partner"],
                        name="core_fee_co_tenant__a7943d_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OrderFee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fee_name", models.CharField(max_length=100)),
                ("fee_type", models.CharField(max_length=20)),
                ("applies_to", models.CharField(max_length=20)),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fees",
                        to="marketplace.order",
                    ),
                ),
            ],
            options={
                "db_table": "core_order_fees",
                "indexes": [
                    models.Index(
                        fields=["order"], name="core_order__order_i_8c53fc_idx"
                    )
                ],
            },
        ),
    ]
