# Generated by Django 5.2.4 on 2026-03-12 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("booking.created", "booking.created"),
                            ("booking.accepted", "booking.accepted"),
                            ("booking.rejected", "booking.rejected"),
                            ("booking.cancelled", "booking.cancelled"),
                            ("payment.pending", "payment.pending"),
                            ("payment.success", "payment.success"),
                            ("payment.failed", "payment.failed"),
                            ("payment.refunded", "payment.refunded"),
                            ("session.reminder", "session.reminder"),
                            ("session.started", "session.started"),
                            ("session.completed", "session.completed"),
                            ("session.cancelled", "session.cancelled"),
                            ("system.announcement", "system.announcement"),
                            ("system.maintenance", "system.maintenance"),
                        ],
                        help_text="booking_accepted, payment_success, session_started, etc",
                        max_length=100,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        default="info",
                        help_text="info | warning | error",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "entity_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("entity_id", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        help_text="Optional structured data for frontend navigation",
                        null=True,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "core_notifications",
                "ordering": ["-created_at"],
            },
        ),
    ]
