# Generated by Django 5.2.4 on 2026-02-27 00:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_notifications", "0003_initial"),
        ("core_tenants", "0005_tenant_platform_fee_percent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="type",
        ),
        migrations.AddField(
            model_name="notification",
            name="entity_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="entity_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="event",
            field=models.CharField(
                choices=[
                    ("booking.created", "booking.created"),
                    ("booking.accepted", "booking.accepted"),
                    ("booking.rejected", "booking.rejected"),
                    ("booking.cancelled", "booking.cancelled"),
                    ("payment.pending", "payment.pending"),
                    ("payment.success", "payment.success"),
                    ("payment.failed", "payment.failed"),
                    ("payment.refunded", "payment.refunded"),
                    ("session.reminder", "session.reminder"),
                    ("session.started", "session.started"),
                    ("session.completed", "session.completed"),
                    ("session.cancelled", "session.cancelled"),
                    ("system.announcement", "system.announcement"),
                    ("system.maintenance", "system.maintenance"),
                ],
                default="system.announcement",
                help_text="booking_accepted, payment_success, session_started, etc",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="notification",
            name="level",
            field=models.CharField(
                default="info", help_text="info | warning | error", max_length=20
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "is_read"], name="core_notifi_user_id_45be03_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "created_at"], name="core_notifi_user_id_79d5a8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["event"], name="core_notifi_event_ff393f_idx"),
        ),
    ]
