# Generated by Django 5.2.4 on 2026-04-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_notifications", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="event",
            field=models.CharField(
                choices=[
                    ("booking.created", "booking.created"),
                    ("booking.accepted", "booking.accepted"),
                    ("booking.rejected", "booking.rejected"),
                    ("booking.cancelled", "booking.cancelled"),
                    ("order.created", "order.created"),
                    ("order.needs_approval", "order.needs_approval"),
                    ("order.accepted", "order.accepted"),
                    ("order.rejected", "order.rejected"),
                    ("order.cancelled", "order.cancelled"),
                    ("order.completed", "order.completed"),
                    ("payment.pending", "payment.pending"),
                    ("payment.success", "payment.success"),
                    ("payment.failed", "payment.failed"),
                    ("payment.refunded", "payment.refunded"),
                    ("session.reminder", "session.reminder"),
                    ("session.started", "session.started"),
                    ("session.completed", "session.completed"),
                    ("session.cancelled", "session.cancelled"),
                    ("system.announcement", "system.announcement"),
                    ("system.maintenance", "system.maintenance"),
                ],
                help_text="booking_accepted, payment_success, session_started, etc",
                max_length=100,
            ),
        ),
    ]
