# Generated by Django 5.2.4 on 2026-03-12 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core_account", "0001_initial"),
        ("core_tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraddress",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_addresses",
                to="core_tenants.tenant",
            ),
        ),
    ]
