# Generated by Django 5.2.4 on 2026-03-12 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core_account", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="useraddress",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="settings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="useraddress",
            index=models.Index(
                fields=["user", "tenant"], name="core_user_a_user_id_fffafb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useraddress",
            index=models.Index(
                fields=["user", "is_default"], name="core_user_a_user_id_6fb359_idx"
            ),
        ),
    ]
