# Generated by Django 5.2.4 on 2026-04-18 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_account", "0004_userbankaccount"),
        ("core_master_banks", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userbankaccount",
            name="bank_name",
        ),
        migrations.AddField(
            model_name="userbankaccount",
            name="bank",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user_accounts",
                to="core_master_banks.bank",
            ),
        ),
    ]
