# Generated by Django 5.2.4 on 2026-04-22 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_account", "0005_remove_userbankaccount_bank_name_and_more"),
        ("core_geo_cities", "0001_initial"),
        ("core_geo_countries", "0004_remove_country_uniq_country_tenant_code_and_more"),
        (
            "core_geo_regions",
            "0004_remove_region_uniq_region_tenant_country_code_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="useraddress",
            name="city_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user_addresses",
                to="core_geo_cities.city",
            ),
        ),
        migrations.AddField(
            model_name="useraddress",
            name="country_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user_addresses",
                to="core_geo_countries.country",
            ),
        ),
        migrations.AddField(
            model_name="useraddress",
            name="region_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user_addresses",
                to="core_geo_regions.region",
            ),
        ),
    ]
