# Generated by Django 5.2.4 on 2026-05-07 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0004_tax"),
    ]

    operations = [
        migrations.AddField(
            model_name="payableinvoice",
            name="tax",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payable_invoices",
                to="accounting.tax",
            ),
        ),
        migrations.AddField(
            model_name="receivableinvoice",
            name="tax",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="receivable_invoices",
                to="accounting.tax",
            ),
        ),
    ]
