# Generated by Django 5.2.4 on 2026-05-09 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0005_payableinvoice_tax_receivableinvoice_tax"),
    ]

    operations = [
        migrations.AddField(
            model_name="payablepayment",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("posted", "Posted"),
                    ("cancelled", "Cancelled"),
                ],
                default="posted",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="journalmapping",
            name="amount_source",
            field=models.CharField(
                help_text="Field dari payload. Contoh: subtotal, tax_amount, total_amount",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="receivableinvoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("posted", "Posted"),
                    ("partial", "Partial Paid"),
                    ("paid", "Paid"),
                    ("cancelled", "Cancelled"),
                    ("void", "Void"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
