# Generated by Django 5.2.4 on 2026-05-11 01:26

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0006_payablepayment_status_and_more"),
        ("core_tenants", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetCategory",
            fields=[
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "depreciation_method",
                    models.CharField(
                        choices=[
                            ("straight_line", "Straight Line"),
                            ("declining_balance", "Declining Balance"),
                            ("manual", "Manual"),
                        ],
                        default="straight_line",
                        max_length=50,
                    ),
                ),
                (
                    "useful_life_months",
                    models.PositiveIntegerField(default=12),
                ),
                (
                    "salvage_value_percent",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "accumulated_depreciation_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asset_category_accumulated_accounts",
                        to="accounting.account",
                    ),
                ),
                (
                    "asset_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asset_category_asset_accounts",
                        to="accounting.account",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "depreciation_expense_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asset_category_expense_accounts",
                        to="accounting.account",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core_tenants.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accounting_asset_categories",
                "ordering": ["code"],
                "unique_together": {("tenant", "code")},
            },
        ),
        migrations.CreateModel(
            name="FixedAsset",
            fields=[
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("asset_number", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("purchase_date", models.DateField()),
                ("capitalization_date", models.DateField()),
                (
                    "purchase_cost",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "salvage_value",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=18
                    ),
                ),
                ("depreciation_method", models.CharField(max_length=50)),
                ("useful_life_months", models.PositiveIntegerField()),
                ("depreciation_start_date", models.DateField()),
                (
                    "last_depreciation_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "accumulated_depreciation",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=18
                    ),
                ),
                (
                    "book_value",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=18
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("fully_depreciated", "Fully Depreciated"),
                            ("disposed", "Disposed"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assets",
                        to="accounting.assetcategory",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core_tenants.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accounting_fixed_assets",
                "ordering": ["-capitalization_date", "asset_number"],
                "unique_together": {("tenant", "asset_number")},
            },
        ),
        migrations.CreateModel(
            name="DepreciationEntry",
            fields=[
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("period_date", models.DateField()),
                (
                    "depreciation_amount",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "accumulated_depreciation",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "book_value_after",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("posted", "Posted"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="depreciation_entries",
                        to="accounting.journal",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core_tenants.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="depreciation_entries",
                        to="accounting.fixedasset",
                    ),
                ),
            ],
            options={
                "db_table": "accounting_depreciation_entries",
                "ordering": ["-period_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AssetDisposal",
            fields=[
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("disposal_date", models.DateField()),
                (
                    "disposal_value",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=18
                    ),
                ),
                (
                    "gain_loss_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=18
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("posted", "Posted"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asset_disposals",
                        to="accounting.journal",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core_tenants.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disposals",
                        to="accounting.fixedasset",
                    ),
                ),
            ],
            options={
                "db_table": "accounting_asset_disposals",
                "ordering": ["-disposal_date", "-created_at"],
            },
        ),
    ]
