# Generated by Django 5.2.4 on 2026-05-11 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounting",
            "0007_assetcategory_fixedasset_depreciationentry_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="fixedasset",
            name="location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="serial_number",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
