# Generated by Django 5.2.4 on 2026-04-15 03:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business_booking", "0003_rename_order_item_id_booking_order_id_and_more"),
        (
            "business_partners",
            "0006_partner_city_partner_country_partner_district_and_more",
        ),
        ("business_reviews", "0001_initial"),
        ("core_tenants", "0002_initial"),
        ("marketplace", "0010_order_subtotal_amount_order_total_fee_amount"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("booking", "user"), name="unique_review_per_booking_user"
            ),
        ),
    ]
