# Generated by Django 5.2.4 on 2026-05-04 00:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_legal", "0001_initial"),
        ("core_tenants", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="policydocument",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="policydocument",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("tenant", "code", "version"),
                name="unique_active_policy_version",
            ),
        ),
    ]
