# Generated by Django 5.2.4 on 2026-01-21 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core_audit_logs", "0001_initial"),
        ("core_tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_logs",
                to="core_tenants.tenant",
            ),
        ),
    ]
